"""Security rules for evaluating EC2 key pairs.

Contains pure Python evaluation logic with no external AWS dependencies.

This rule set is deliberately short, and the reason is worth stating rather
than hiding. AWS stores almost nothing about a key pair: a name, a type, a
fingerprint and a creation time. It does not store the key length, so an
undersized RSA key is invisible here. It does not record whether the key was
imported or generated by AWS, so the very property this tool cares most about
cannot be verified after the fact. And a private key's real risk is where it is
stored and who has copied it, none of which is knowable from the cloud side.

Padding this file with checks that look thorough would be worse than admitting
the limit. Two findings are genuine and both are here.

No published benchmark covers EC2 key pairs, so nothing here carries a
citation.
"""

from scanner.common import (
    CRITICAL,
    WARNING,
    INFO,
    warning as _warning,
    summarize,
    fixable,
    cited,
    worst_level,
    print_warnings,
)


def _target(key_name, setting):
    return {
        "rule_id": f"{key_name}:{setting}",
        "resource_id": key_name,
        "setting": setting,
    }


def check_key_pair(settings):
    """Evaluates one key pair and returns detected risks.

    Expects the shape produced by aws.key_pairs.read_key_pair_for_scanning():
        {
          "key_name": str,
          "key_type": "ED25519" | "RSA" | "",
          "fingerprint": str,
          "in_use": bool,
          "managed_by_us": bool,
        }
    """
    if not settings:
        return []

    name = settings.get("key_name", "unknown")
    warnings = []

    # ---- Key type ------------------------------------------------------------
    if settings.get("key_type") == "RSA":
        warnings.append(_warning(
            INFO,
            "This is an RSA key. ED25519 keys are shorter, faster to verify and "
            "at least as strong, and every current version of OpenSSH supports "
            "them. This is a preference rather than a problem: AWS does not "
            "record how long an RSA key is, so this tool cannot tell a strong "
            "one from a weak one. If you know it is a 1024-bit key, replace it.",
            _target(name, "key_type"),
        ))

    # ---- Usage ---------------------------------------------------------------
    if not settings.get("in_use"):
        warnings.append(_warning(
            INFO,
            "No running or stopped instance uses this key. An unused key is not "
            "dangerous by itself, but every copy of its private half is still a "
            "way in if it is ever attached to something, and nobody thinks to "
            "protect a key they believe is retired. Delete it if it is finished "
            "with.",
            _target(name, "unused"),
        ))

    return warnings
